name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-16.04

variables:
  subscription: "Dev-Alv-Subscription-Azure-Service-Connection"

stages:
  - stage: Build
    jobs:
      - job: common
        steps:
          - task: Bash@3
            name: setvarStep
            displayName: Set variables
            inputs:
              targetType: inline
              script: |
                ## At least 7 digits, more if needed for uniqueness
                SHORT_HASH=`git rev-parse --short=7 HEAD`
                echo "Short hash set to $SHORT_HASH"
                echo "##vso[task.setvariable variable=git-short-hash;isOutput=true]$SHORT_HASH"

      - job: infrastructure
        variables:
          - group: alvtime-test
          - name: env
            value: test
          - name: tf-state-storage-account
            value: "terraformstatealvtest"
        steps:
          - template: ../../packages/infrastructure/build-steps.yaml

      - job: frontend
        dependsOn: common
        variables:
          git-short-hash: $[ dependencies.common.outputs['setvarStep.git-short-hash'] ]
        steps:
          - template: ../../packages/frontend/build-steps.yaml

      - job: adminpanel
        dependsOn: common
        variables:
          git-short-hash: $[ dependencies.common.outputs['setvarStep.git-short-hash'] ]
        steps:
          - template: ../../packages/adminpanel/build-steps.yaml

      - job: api
        dependsOn: common
        variables:
          git-short-hash: $[ dependencies.common.outputs['setvarStep.git-short-hash'] ]
        steps:
          - template: ../../packages/api/build-steps.yaml

      - job: slack
        dependsOn: common
        variables:
          git-short-hash: $[ dependencies.common.outputs['setvarStep.git-short-hash'] ]
        steps:
          - template: ../../packages/slack-app/build-steps.yaml

      - job: chart
        dependsOn: common
        variables:
          git-short-hash: $[ dependencies.common.outputs['setvarStep.git-short-hash'] ]
        steps:
          - template: ../../packages/chart/build-steps.yaml

  - stage: test
    jobs:
      - deployment: test
        variables:
          - group: alvtime-test
          - name: env
            value: test
          - name: tf-state-storage-account
            value: "terraformstatealvtest"
          - name: subscription
            value: "Dev-Alv-Subscription-Azure-Service-Connection"
          - name: git-short-hash
            value: $[ stageDependencies.Build.common.outputs['setvarStep.git-short-hash'] ]
        displayName: Test
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../../packages/infrastructure/deploy-steps.yaml
                - template: ../../packages/chart/deploy-steps.yaml
