name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-22.04

stages:
  - stage: testbuild
    displayName: Test environment
    variables:
      - group: azure-credentials-test
    jobs:
      - job: testbuild
        displayName: Plan and build
        steps:
          - checkout: self
            fetchDepth: 1

          - template: installDependencies.yaml

          - task: AzureCLI@2
            displayName: Run build.sh test ---no-input
            inputs:
              azureSubscription: 'k8s-test-subscription(18d83c2a-79e0-48b2-a49a-0244de28de8c)'
              addSpnToEnvironment: true
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Authenticate Acure container registry
                docker login alvkubernetesclustertestacr.azurecr.io \
                  --username $(azure-service-principal-username) \
                  --password $(azure-service-principal-password)

                # Run scripts to build for test environment
                source scripts/setup.sh test --no-input
                source scripts/buildServices.sh
                source scripts/pushServices.sh

  - stage: test
    displayName: Test environment
    jobs:
      - deployment: test
        displayName: Deploy
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1

                - template: installDependencies.yaml

                - task: AzureCLI@2
                  displayName: Run deployment scripts
                  inputs:
                    azureSubscription: 'k8s-test-subscription(18d83c2a-79e0-48b2-a49a-0244de28de8c)'
                    addSpnToEnvironment: true
                    workingDirectory: "$(System.DefaultWorkingDirectory)"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      source scripts/setup.sh test --no-input
                      source scripts/deployServices.sh

  - stage: prod
    displayName: Production environment
    jobs:
      - deployment: prod
        displayName: Deploy
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1

                - template: installDependencies.yaml

                - task: AzureCLI@2
                  displayName: Run deploy.sh prod ---no-input
                  inputs:
                    azureSubscription: 'k8s-prod-subscription(31b6ed1b-2e24-4cf2-8583-874cd21a84e1)'
                    addSpnToEnvironment: true
                    workingDirectory: "$(System.DefaultWorkingDirectory)"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      # Run build script for production env
                      source scripts/setup.sh prod --no-input
                      source scripts/deployServices.sh
