name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-18.04

stages:
  - stage: testbuild
    displayName: Test environment
    jobs:
      - job: testbuild
        displayName: Plan and build
        steps:
          - checkout: self
            fetchDepth: 1

          - template: installDependencies.yaml

          - task: AzureCLI@2
            displayName: Run build.sh test ---no-input
            inputs:
              azureSubscription: Dev-Alv-Subscription-Azure-Service-Connection
              addSpnToEnvironment: true
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Authenticate Acure container registry
                docker login acralvtime.azurecr.io \
                  --username $servicePrincipalId \
                  --password $servicePrincipalKey

                # Run scripts to build for test environment
                source scripts/setup.sh test --no-input
                source scripts/buildServices.sh
                source scripts/pushServices.sh

  - stage: test
    displayName: Test environment
    jobs:
      - deployment: test
        displayName: Deploy
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1

                - template: installDependencies.yaml

                - task: AzureCLI@2
                  displayName: Run deployment scripts
                  inputs:
                    azureSubscription: Dev-Alv-Subscription-Azure-Service-Connection
                    addSpnToEnvironment: true
                    workingDirectory: "$(System.DefaultWorkingDirectory)"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      source scripts/setup.sh test --no-input
                      source scripts/deployServices.sh

  - stage: prod
    displayName: Production environment
    jobs:
      - deployment: prod
        displayName: Deploy
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1

                - template: installDependencies.yaml

                - task: AzureCLI@2
                  displayName: Run deploy.sh prod ---no-input
                  inputs:
                    azureSubscription: Pay-As-You-Go (f9b4e4d2-39a5-4c35-876c-303dc3de03d2)
                    addSpnToEnvironment: true
                    workingDirectory: "$(System.DefaultWorkingDirectory)"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      # Run build script for production env
                      source scripts/setup.sh prod --no-input
                      source scripts/deployServices.sh
