version: '3.7'

services:
  alvtime-vue-local-build:
    container_name: alvtime-vue-local-build
    tty: true
    image: alvtime-vue-local-build
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VUE_APP_HOST: http://localhost
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    expose:
      - 80
  nginx-reverse-proxy-local-build:
    container_name: nginx-reverse-proxy-local-build
    build:
      context: ./nginx
      dockerfile: ./Dockerfile-local-build
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    links:
      - dotnet-backend
      - alvtime-vue-local-build
  dotnet-backend:
    container_name: dotnet-backend
    image: alvnoas/alvtime-web-api:latest
    links:
      - mssql-db
    expose:
      - "80"
  mssql-db:
    container_name: mssql-db
    image: alvnoas/alvtime-database:latest
    expose:
      - "1433"
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # So that the container doesn't shut down, sleep this thread
        sleep infinity
