#!/usr/bin/env bash

[ "up" = "$1" ] && \
  docker-compose up --detach

if [ "frontend" = "$1" ]; then
  docker-compose up -d && \
    docker-compose exec frontend npm start
fi

if [ "adminpanel" = "$1" ]; then
  docker-compose up -d && \
    docker-compose exec adminpanel npm start
fi

[ "down" = "$1" ] && \
  docker-compose down --volumes

[ "logs" = "$1" ] && \
  docker-compose logs --follow

[ "test" = "$1" ] && \
  docker-compose exec alvtime-admin-react-pwa npm test

[ "prune" = "$1" ] && \
  docker system prune --force

# export ARM_ACCESS_KEY=$(run get-access-key)
[ "get-access-key" = "$1" ] && \
  az storage account keys list \
  --subscription 'Dev-Alv' \
  --resource-group 'Alvtime-common' \
  --account-name 'terraformstatealvdev' \
  | jq -r '.[0].value'

[ "configure-kubectl" = "$1" ] && \
  az aks get-credentials \
  --subscription 'Dev-Alv' \
  --resource-group 'aks-resource-group' \
  --name 'alvtime-aks'
