#!/usr/bin/env sh

[ "frontend" = "$1" ] && \
  docker-compose up --detach && \
  docker-compose exec alvtime-vue-pwa npx vue-cli-service serve

[ "adminpanel" = "$1" ] && \
  docker-compose up --detach && \
  docker-compose exec alvtime-admin-react-pwa npx react-scripts start

[ "bash" = "$1" ] && \
  docker-compose up --detach && \
  docker-compose exec alvtime-vue-pwa bash

[ "up" = "$1" ] && \
  docker-compose up --detach

[ "down" = "$1" ] && \
  docker-compose down --volumes

[ "logs" = "$1" ] && \
  docker-compose logs --follow

[ "pull" = "$1" ] && \
  docker-compose pull

[ "build" = "$1" ] && \
  docker-compose build

[ "test" = "$1" ] && \
  docker-compose exec alvtime-admin-react-pwa npx react-scripts test

[ "prune" = "$1" ] && \
  docker system prune --force

exit 0
