version: "3.7"
services:
  dotnet-backend:
    container_name: dotnet-backend
    build: ./
    links:
      - mssql-db
    env_file:
      - ../AlvTimeWebApi/.env
    ports:
      - "8000:80"
    environment:
      - AdminGroup=5850c192-c101-4b64-9c45-cbbf73542805

  mssql-db:
    container_name: mssql-db
    build: ./AlvTime.Persistence/Database
    volumes:
     - ./Database/:/scripts/
    ports:
      - "1433:1433"
