version: "3.7"

services:
  alvtime-vue-pwa:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VUE_APP_API_HOST: "http://localhost"
        VUE_APP_ACCESS_SCOPE: "https://d8aedd.alvtime-ap-alvtime-api-dev-f9b4e4.westeurope.cloudapp.azure.com/access_as_user"
        VUE_APP_CLIENT_ID: "373a7768-6d2a-4b20-b671-bc1089104a3a"
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    expose:
      - 80

  nginx-reverse-proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile-local-build
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    links:
      - dotnet-backend
      - alvtime-vue-local-build

  alvtime-web-api:
    image: alvnoas/alvtime-web-api:latest
    links:
      - mssql-db
    environment:
      - ConnectionStrings__AlvTime_db=Data Source=tcp:mssql-db,1433;Initial Catalog=AlvDevDB;User ID=sa;Password=AlvTimeTestErMoro32
    expose:
      - "80"

  mssql-db:
    image: alvnoas/alvtime-database:latest
    expose:
      - "1433"
    ports:
      - "1433:1433"
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # So that the container doesn't shut down, sleep this thread
        sleep infinity
