steps:
  - checkout: self
    fetchDepth: 1

  - task: PublishBuildArtifacts@1
    displayName: Publish folder as build artifact
    inputs:
      pathtoPublish: packages/chart
      artifactName: chart
