apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          azuredns:
            clientID: {{ .Values.client.id }}
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: {{ .Values.subscriptionID }}
            tenantID: {{ .Values.tenantID }}
            resourceGroupName: {{ .Values.resourceGroupName }}
            hostedZoneName: {{ .Values.hostedZoneName }}
            environment: AzurePublicCloud
