//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alvtime.Adminpanel.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedContentStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedContentStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alvtime.Adminpanel.Client.Resources.SharedContentStrings", typeof(SharedContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmployeesPage_Title {
            get {
                return ResourceManager.GetString("EmployeesPage.Title", resourceCulture);
            }
        }
        
        internal static string EmployeesPage_Alver {
            get {
                return ResourceManager.GetString("EmployeesPage.Alver", resourceCulture);
            }
        }
        
        internal static string Common_SaveChanges {
            get {
                return ResourceManager.GetString("Common.SaveChanges", resourceCulture);
            }
        }
        
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        internal static string Common_SortBy {
            get {
                return ResourceManager.GetString("Common.SortBy", resourceCulture);
            }
        }
        
        internal static string EmployeesPage_AddEmployee {
            get {
                return ResourceManager.GetString("EmployeesPage.AddEmployee", resourceCulture);
            }
        }
        
        internal static string Common_Name {
            get {
                return ResourceManager.GetString("Common.Name", resourceCulture);
            }
        }
        
        internal static string Common_Email {
            get {
                return ResourceManager.GetString("Common.Email", resourceCulture);
            }
        }
        
        internal static string Common_StartDate {
            get {
                return ResourceManager.GetString("Common.StartDate", resourceCulture);
            }
        }
        
        internal static string Common_EndDate {
            get {
                return ResourceManager.GetString("Common.EndDate", resourceCulture);
            }
        }
        
        internal static string Common_EmployeeId {
            get {
                return ResourceManager.GetString("Common.EmployeeId", resourceCulture);
            }
        }
        
        internal static string Common_Login {
            get {
                return ResourceManager.GetString("Common.Login", resourceCulture);
            }
        }
        
        internal static string Common_Logout {
            get {
                return ResourceManager.GetString("Common.Logout", resourceCulture);
            }
        }
        
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        internal static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation.Name.Required", resourceCulture);
            }
        }
        
        internal static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation.Email.Required", resourceCulture);
            }
        }
        
        internal static string Validation_Email_NotValid {
            get {
                return ResourceManager.GetString("Validation.Email.NotValid", resourceCulture);
            }
        }
        
        internal static string Validation_Date_TodayOrFuture {
            get {
                return ResourceManager.GetString("Validation.Date.TodayOrFuture", resourceCulture);
            }
        }
        
        internal static string Validation_Date_Future {
            get {
                return ResourceManager.GetString("Validation.Date.Future", resourceCulture);
            }
        }
        
        internal static string Validation_Date_Required {
            get {
                return ResourceManager.GetString("Validation.Date.Required", resourceCulture);
            }
        }
        
        internal static string Validation_EmployeeId_Required {
            get {
                return ResourceManager.GetString("Validation.EmployeeId.Required", resourceCulture);
            }
        }
        
        internal static string Validation_EmployeeId_NotValid {
            get {
                return ResourceManager.GetString("Validation.EmployeeId.NotValid", resourceCulture);
            }
        }
    }
}
