//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alvtime.Adminpanel.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedContentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedContentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alvtime.Adminpanel.Client.Resources.SharedContentStrings", typeof(SharedContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive timekoder.
        /// </summary>
        internal static string Common_ActiveTasks {
            get {
                return ResourceManager.GetString("Common.ActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alvtime adminpanel.
        /// </summary>
        internal static string Common_AppTitle {
            get {
                return ResourceManager.GetString("Common.AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selskapsinformasjon.
        /// </summary>
        internal static string Common_CompanyInformation {
            get {
                return ResourceManager.GetString("Common.CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtidsfaktor.
        /// </summary>
        internal static string Common_CompensationRate {
            get {
                return ResourceManager.GetString("Common.CompensationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformasjon.
        /// </summary>
        internal static string Common_ContactInformation {
            get {
                return ResourceManager.GetString("Common.ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson.
        /// </summary>
        internal static string Common_ContactPerson {
            get {
                return ResourceManager.GetString("Common.ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        internal static string Common_Description {
            get {
                return ResourceManager.GetString("Common.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost.
        /// </summary>
        internal static string Common_Email {
            get {
                return ResourceManager.GetString("Common.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansattnummer.
        /// </summary>
        internal static string Common_EmployeeId {
            get {
                return ResourceManager.GetString("Common.EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stillingsprosent.
        /// </summary>
        internal static string Common_EmploymentRate {
            get {
                return ResourceManager.GetString("Common.EmploymentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stillingsprosenter.
        /// </summary>
        internal static string Common_EmploymentRates {
            get {
                return ResourceManager.GetString("Common.EmploymentRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttdato.
        /// </summary>
        internal static string Common_EndDate {
            get {
                return ResourceManager.GetString("Common.EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttdato (inkl.).
        /// </summary>
        internal static string Common_EndDate_Inclusive {
            get {
                return ResourceManager.GetString("Common.EndDate.Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timerater.
        /// </summary>
        internal static string Common_HourRates {
            get {
                return ResourceManager.GetString("Common.HourRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rater per side.
        /// </summary>
        internal static string Common_HourRates_Pagination_PerPage {
            get {
                return ResourceManager.GetString("Common.HourRates.Pagination.PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pålagt.
        /// </summary>
        internal static string Common_Imposed {
            get {
                return ResourceManager.GetString("Common.Imposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasjon.
        /// </summary>
        internal static string Common_Information {
            get {
                return ResourceManager.GetString("Common.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturaadresse.
        /// </summary>
        internal static string Common_InvoiceAddress {
            get {
                return ResourceManager.GetString("Common.InvoiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låst.
        /// </summary>
        internal static string Common_Locked {
            get {
                return ResourceManager.GetString("Common.Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        internal static string Common_Login {
            get {
                return ResourceManager.GetString("Common.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg ut.
        /// </summary>
        internal static string Common_Logout {
            get {
                return ResourceManager.GetString("Common.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        internal static string Common_Name {
            get {
                return ResourceManager.GetString("Common.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå til.
        /// </summary>
        internal static string Common_NavigateTo {
            get {
                return ResourceManager.GetString("Common.NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nei.
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org.nummer.
        /// </summary>
        internal static string Common_OrgNr {
            get {
                return ResourceManager.GetString("Common.OrgNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        internal static string Common_Pagination_All {
            get {
                return ResourceManager.GetString("Common.Pagination.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjekt.
        /// </summary>
        internal static string Common_Project {
            get {
                return ResourceManager.GetString("Common.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjekter.
        /// </summary>
        internal static string Common_Projects {
            get {
                return ResourceManager.GetString("Common.Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjekter per side.
        /// </summary>
        internal static string Common_Projects_Pagination_PerPage {
            get {
                return ResourceManager.GetString("Common.Projects.Pagination.PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Common_Rate {
            get {
                return ResourceManager.GetString("Common.Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre endringer.
        /// </summary>
        internal static string Common_SaveChanges {
            get {
                return ResourceManager.GetString("Common.SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        internal static string Common_Search {
            get {
                return ResourceManager.GetString("Common.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorter etter.
        /// </summary>
        internal static string Common_SortBy {
            get {
                return ResourceManager.GetString("Common.SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdato.
        /// </summary>
        internal static string Common_StartDate {
            get {
                return ResourceManager.GetString("Common.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra dato (inkl.).
        /// </summary>
        internal static string Common_StartDate_Inclusive {
            get {
                return ResourceManager.GetString("Common.StartDate.Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timekode.
        /// </summary>
        internal static string Common_Task {
            get {
                return ResourceManager.GetString("Common.Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timekoder.
        /// </summary>
        internal static string Common_Tasks {
            get {
                return ResourceManager.GetString("Common.Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timekoder per side.
        /// </summary>
        internal static string Common_Tasks_Pagination_PerPage {
            get {
                return ResourceManager.GetString("Common.Tasks.Pagination.PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Common_Telephone {
            get {
                return ResourceManager.GetString("Common.Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stk.
        /// </summary>
        internal static string Common_Unit_Pcs {
            get {
                return ResourceManager.GetString("Common.Unit.Pcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall på prosjektet.
        /// </summary>
        internal static string Common_UsingProject {
            get {
                return ResourceManager.GetString("Common.UsingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til timerate.
        /// </summary>
        internal static string CustomerPage_AddHourRate {
            get {
                return ResourceManager.GetString("CustomerPage.AddHourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til prosjekt.
        /// </summary>
        internal static string CustomerPage_AddProject {
            get {
                return ResourceManager.GetString("CustomerPage.AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til timekode.
        /// </summary>
        internal static string CustomerPage_AddTask {
            get {
                return ResourceManager.GetString("CustomerPage.AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett timerate.
        /// </summary>
        internal static string CustomerPage_DeleteHourRate {
            get {
                return ResourceManager.GetString("CustomerPage.DeleteHourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre kunde.
        /// </summary>
        internal static string CustomerPage_EditCustomer {
            get {
                return ResourceManager.GetString("CustomerPage.EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre timerate.
        /// </summary>
        internal static string CustomerPage_EditHourRate {
            get {
                return ResourceManager.GetString("CustomerPage.EditHourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre prosjekt.
        /// </summary>
        internal static string CustomerPage_EditProject {
            get {
                return ResourceManager.GetString("CustomerPage.EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre timekode.
        /// </summary>
        internal static string CustomerPage_EditTask {
            get {
                return ResourceManager.GetString("CustomerPage.EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunder per side:.
        /// </summary>
        internal static string CustomerPage_Pagination_PerPage {
            get {
                return ResourceManager.GetString("CustomerPage.Pagination.PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny kunde.
        /// </summary>
        internal static string CustomersPage_AddCustomer {
            get {
                return ResourceManager.GetString("CustomersPage.AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunder.
        /// </summary>
        internal static string CustomersPage_Title {
            get {
                return ResourceManager.GetString("CustomersPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til stillingsprosent.
        /// </summary>
        internal static string EmployeePage_AddEmploymentRate {
            get {
                return ResourceManager.GetString("EmployeePage.AddEmploymentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansattdetaljer.
        /// </summary>
        internal static string EmployeePage_Details {
            get {
                return ResourceManager.GetString("EmployeePage.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre ansatt.
        /// </summary>
        internal static string EmployeePage_EditEmployee {
            get {
                return ResourceManager.GetString("EmployeePage.EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre stillingsprosent.
        /// </summary>
        internal static string EmployeePage_EditEmploymentRate {
            get {
                return ResourceManager.GetString("EmployeePage.EditEmploymentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny Alv.
        /// </summary>
        internal static string EmployeesPage_AddEmployee {
            get {
                return ResourceManager.GetString("EmployeesPage.AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alver.
        /// </summary>
        internal static string EmployeesPage_Employees {
            get {
                return ResourceManager.GetString("EmployeesPage.Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alver per side.
        /// </summary>
        internal static string EmployeesPage_Pagination_PerPage {
            get {
                return ResourceManager.GetString("EmployeesPage.Pagination.PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansatte.
        /// </summary>
        internal static string EmployeesPage_Title {
            get {
                return ResourceManager.GetString("EmployeesPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtidsfaktor må fylles inn.
        /// </summary>
        internal static string Validation_CompensationRate_Required {
            get {
                return ResourceManager.GetString("Validation.CompensationRate.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoen må være fremover i tid.
        /// </summary>
        internal static string Validation_Date_Future {
            get {
                return ResourceManager.GetString("Validation.Date.Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoren må fylles inn.
        /// </summary>
        internal static string Validation_Date_Required {
            get {
                return ResourceManager.GetString("Validation.Date.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoen må være i dag eller senere.
        /// </summary>
        internal static string Validation_Date_TodayOrFuture {
            get {
                return ResourceManager.GetString("Validation.Date.TodayOrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utfyllt epost er ikke gyldig.
        /// </summary>
        internal static string Validation_Email_NotValid {
            get {
                return ResourceManager.GetString("Validation.Email.NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost må fylles inn.
        /// </summary>
        internal static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation.Email.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansattnummer er ikke gyldig.
        /// </summary>
        internal static string Validation_EmployeeId_NotValid {
            get {
                return ResourceManager.GetString("Validation.EmployeeId.NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansattnummer må fylles inn.
        /// </summary>
        internal static string Validation_EmployeeId_Required {
            get {
                return ResourceManager.GetString("Validation.EmployeeId.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timerate må fylle inn.
        /// </summary>
        internal static string Validation_HourRate_Required {
            get {
                return ResourceManager.GetString("Validation.HourRate.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn må fylles inn.
        /// </summary>
        internal static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation.Name.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer må fylles ut.
        /// </summary>
        internal static string Validation_OrgNr_Required {
            get {
                return ResourceManager.GetString("Validation.OrgNr.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjekt må velges.
        /// </summary>
        internal static string Validation_Project_Required {
            get {
                return ResourceManager.GetString("Validation.Project.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timekode må velges.
        /// </summary>
        internal static string Validation_Task_Required {
            get {
                return ResourceManager.GetString("Validation.Task.Required", resourceCulture);
            }
        }
    }
}
