//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alvtime.Adminpanel.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedContentStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedContentStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alvtime.Adminpanel.Client.Resources.SharedContentStrings", typeof(SharedContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmployeesPage_Title {
            get {
                return ResourceManager.GetString("EmployeesPage.Title", resourceCulture);
            }
        }
        
        internal static string EmployeesPage_Alver {
            get {
                return ResourceManager.GetString("EmployeesPage.Alver", resourceCulture);
            }
        }
        
        internal static string Common_SaveChanges {
            get {
                return ResourceManager.GetString("Common.SaveChanges", resourceCulture);
            }
        }
        
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        internal static string Common_SortBy {
            get {
                return ResourceManager.GetString("Common.SortBy", resourceCulture);
            }
        }
        
        internal static string EmployeesPage_AddEmployee {
            get {
                return ResourceManager.GetString("EmployeesPage.AddEmployee", resourceCulture);
            }
        }
        
        internal static string Common_Name {
            get {
                return ResourceManager.GetString("Common.Name", resourceCulture);
            }
        }
        
        internal static string Common_Email {
            get {
                return ResourceManager.GetString("Common.Email", resourceCulture);
            }
        }
        
        internal static string Common_StartDate {
            get {
                return ResourceManager.GetString("Common.StartDate", resourceCulture);
            }
        }
        
        internal static string Common_EndDate {
            get {
                return ResourceManager.GetString("Common.EndDate", resourceCulture);
            }
        }
        
        internal static string Common_EmployeeId {
            get {
                return ResourceManager.GetString("Common.EmployeeId", resourceCulture);
            }
        }
        
        internal static string Common_Login {
            get {
                return ResourceManager.GetString("Common.Login", resourceCulture);
            }
        }
        
        internal static string Common_Logout {
            get {
                return ResourceManager.GetString("Common.Logout", resourceCulture);
            }
        }
        
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        internal static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation.Name.Required", resourceCulture);
            }
        }
        
        internal static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation.Email.Required", resourceCulture);
            }
        }
        
        internal static string Validation_Email_NotValid {
            get {
                return ResourceManager.GetString("Validation.Email.NotValid", resourceCulture);
            }
        }
        
        internal static string Validation_Date_TodayOrFuture {
            get {
                return ResourceManager.GetString("Validation.Date.TodayOrFuture", resourceCulture);
            }
        }
        
        internal static string Validation_Date_Future {
            get {
                return ResourceManager.GetString("Validation.Date.Future", resourceCulture);
            }
        }
        
        internal static string Validation_Date_Required {
            get {
                return ResourceManager.GetString("Validation.Date.Required", resourceCulture);
            }
        }
        
        internal static string Validation_EmployeeId_Required {
            get {
                return ResourceManager.GetString("Validation.EmployeeId.Required", resourceCulture);
            }
        }
        
        internal static string Validation_EmployeeId_NotValid {
            get {
                return ResourceManager.GetString("Validation.EmployeeId.NotValid", resourceCulture);
            }
        }
        
        internal static string Common_AppTitle {
            get {
                return ResourceManager.GetString("Common.AppTitle", resourceCulture);
            }
        }
        
        internal static string CustomersPage_Title {
            get {
                return ResourceManager.GetString("CustomersPage.Title", resourceCulture);
            }
        }
        
        internal static string CustomersPage_AddCustomer {
            get {
                return ResourceManager.GetString("CustomersPage.AddCustomer", resourceCulture);
            }
        }
        
        internal static string Common_OrgNr {
            get {
                return ResourceManager.GetString("Common.OrgNr", resourceCulture);
            }
        }
        
        internal static string Common_InvoiceAddress {
            get {
                return ResourceManager.GetString("Common.InvoiceAddress", resourceCulture);
            }
        }
        
        internal static string Common_ContactPerson {
            get {
                return ResourceManager.GetString("Common.ContactPerson", resourceCulture);
            }
        }
        
        internal static string Common_Telephone {
            get {
                return ResourceManager.GetString("Common.Telephone", resourceCulture);
            }
        }
        
        internal static string Validation_OrgNr_Required {
            get {
                return ResourceManager.GetString("Validation.OrgNr.Required", resourceCulture);
            }
        }
        
        internal static string CustomerPage_Pagination_PerPage {
            get {
                return ResourceManager.GetString("CustomerPage.Pagination.PerPage", resourceCulture);
            }
        }
        
        internal static string Common_Pagination_All {
            get {
                return ResourceManager.GetString("Common.Pagination.All", resourceCulture);
            }
        }
        
        internal static string Common_ContactInformation {
            get {
                return ResourceManager.GetString("Common.ContactInformation", resourceCulture);
            }
        }
        
        internal static string Common_CompanyInformation {
            get {
                return ResourceManager.GetString("Common.CompanyInformation", resourceCulture);
            }
        }
        
        internal static string CustomerPage_AddProject {
            get {
                return ResourceManager.GetString("CustomerPage.AddProject", resourceCulture);
            }
        }
        
        internal static string Common_ActiveTasks {
            get {
                return ResourceManager.GetString("Common.ActiveTasks", resourceCulture);
            }
        }
        
        internal static string Common_UsingProject {
            get {
                return ResourceManager.GetString("Common.UsingProject", resourceCulture);
            }
        }
        
        internal static string Common_Projects {
            get {
                return ResourceManager.GetString("Common.Projects", resourceCulture);
            }
        }
        
        internal static string Common_Description {
            get {
                return ResourceManager.GetString("Common.Description", resourceCulture);
            }
        }
        
        internal static string Common_Project {
            get {
                return ResourceManager.GetString("Common.Project", resourceCulture);
            }
        }
        
        internal static string Common_Tasks {
            get {
                return ResourceManager.GetString("Common.Tasks", resourceCulture);
            }
        }
        
        internal static string CustomerPage_AddTask {
            get {
                return ResourceManager.GetString("CustomerPage.AddTask", resourceCulture);
            }
        }
        
        internal static string Common_Imposed {
            get {
                return ResourceManager.GetString("Common.Imposed", resourceCulture);
            }
        }
        
        internal static string Common_Locked {
            get {
                return ResourceManager.GetString("Common.Locked", resourceCulture);
            }
        }
        
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        internal static string Common_Unit_Pcs {
            get {
                return ResourceManager.GetString("Common.Unit.Pcs", resourceCulture);
            }
        }
        
        internal static string Common_Tasks_Pagination_PerPage {
            get {
                return ResourceManager.GetString("Common.Tasks.Pagination.PerPage", resourceCulture);
            }
        }
        
        internal static string Common_Projects_Pagination_PerPage {
            get {
                return ResourceManager.GetString("Common.Projects.Pagination.PerPage", resourceCulture);
            }
        }
        
        internal static string Common_HourRates {
            get {
                return ResourceManager.GetString("Common.HourRates", resourceCulture);
            }
        }
        
        internal static string CustomerPage_AddHourRate {
            get {
                return ResourceManager.GetString("CustomerPage.AddHourRate", resourceCulture);
            }
        }
        
        internal static string Common_StartDate_Inclusive {
            get {
                return ResourceManager.GetString("Common.StartDate.Inclusive", resourceCulture);
            }
        }
        
        internal static string Common_Rate {
            get {
                return ResourceManager.GetString("Common.Rate", resourceCulture);
            }
        }
        
        internal static string Common_Task {
            get {
                return ResourceManager.GetString("Common.Task", resourceCulture);
            }
        }
        
        internal static string Common_HourRates_Pagination_PerPage {
            get {
                return ResourceManager.GetString("Common.HourRates.Pagination.PerPage", resourceCulture);
            }
        }
        
        internal static string Common_CompensationRate {
            get {
                return ResourceManager.GetString("Common.CompensationRate", resourceCulture);
            }
        }
        
        internal static string Validation_Project_Required {
            get {
                return ResourceManager.GetString("Validation.Project.Required", resourceCulture);
            }
        }
        
        internal static string Validation_CompensationRate_Required {
            get {
                return ResourceManager.GetString("Validation.CompensationRate.Required", resourceCulture);
            }
        }
        
        internal static string Validation_Task_Required {
            get {
                return ResourceManager.GetString("Validation.Task.Required", resourceCulture);
            }
        }
        
        internal static string Validation_HourRate_Required {
            get {
                return ResourceManager.GetString("Validation.HourRate.Required", resourceCulture);
            }
        }
    }
}
