name: Adminpanel Build And Test

on:
  pull_request:
    paths:
      - "packages/adminpanel/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: "./packages/adminpanel"
        run: docker build . --file Dockerfile --tag image
