name: api-docker-publish-releases

on:
  push:
    branches:
      - releases/*

env:
  IMAGE_NAME: alvnoas/alvtime-web-api

jobs:
  # Push image to Docker Hub
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build api image
        working-directory: "./packages/api"
        run: docker build . --tag image

      - uses: anchore/scan-action@v2
        with:
          image: image:latest
          fail-build: true
          severity-cutoff: critical

      - name: grype scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push api image
        run: |

          echo IMAGE_NAME=$IMAGE_NAME

          docker tag image $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
