name: API workflow-runner 

on:
    workflow_dispatch:
    push:
        branches:
          - master
        paths:
         - "packages/api/**"
         
jobs:
    build-and-deploy-test:
        uses: ./.github/workflows/api-build-and-deploy.yml
        with: 
            targetEnv: test
        secrets: inherit

    build-and-deploy-prod:
        needs: build-and-deploy-test
        uses: ./.github/workflows/api-build-and-deploy.yml
        with:
            targetEnv: prod  
        secrets: inherit
