name: Build and test API

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore
      working-directory: packages/api/

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: packages/api/

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: packages/api/
