name: Frontend workflow-runner

on:
  push:
    branches:
      - staticwebappFront
      
jobs:
    build-and-deploy-test:
        uses: ./.github/workflows/frontend-build-and-deploy.yml
        with: 
            targetEnv: test
        secrets: inherit

    build-and-deploy-prod:
        uses: ./.github/workflows/frontend-build-and-deploy.yml
        with: 
            targetEnv: prod