name: Frontend workflow-runner

on:
  push:
    branches:
      - staticwebappFront
      
jobs:
    build-and-deploy-test:
      runs-on: ubuntu-latest
      steps: 
        - name: Symlink Correct Workflow File
          run: ln -s .github/workflows/azure-static-web-apps-red-sand-043c70a03.yml .github/workflows/azure-static-web-apps-red-sand-043c70a03.yml
        - name: Run Workflow
          uses: ./.github/workflows/frontend-build-and-deploy.yml
          with: 
              targetEnv: test
          secrets: inherit

    build-and-deploy-prod:
      steps: 
        - name: Symlink Correct Workflow File
          run: ln -s .github/workflows/azure-static-web-apps-red-sand-043c70a03.yml .github/workflows/azure-static-web-apps-mango-island-0a2b55803.yml
        - name: Run Workflow
          needs: build-and-deploy-test
          uses: ./.github/workflows/frontend-build-and-deploy.yml
          with: 
              targetEnv: prod
          secrets: inherit