name: Frontend V3 Build and Deploy Prod

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Frontend V3 Build and Deploy Test"]
    types:
      - completed 

jobs:
  build_and_deploy_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build and Deploy to Prod Job
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false	
      - name: Set config
        working-directory: packages/frontend-v3
        run: cp public/config.prod.json public/config.json
      - name: Debug token presence
        run: echo ${{secrets.STATICWEBAPP_V3_DEPLOYMENT_TOKEN}} | sed 's/./& /g'
        env:
          STATICWEBAPP_V3_DEPLOYMENT_TOKEN: ${{ secrets.STATICWEBAPP_V3_DEPLOYMENT_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STATICWEBAPP_V3_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./packages/frontend-v3" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######