name: Docker

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

    branches:
      - master

env:
  IMAGE_NAME: alvnoas/alvtime-vue-pwa

jobs:
  # Push image to Docker Hub
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag image \
          --build-arg VUE_APP_HOST=https://alvtime-api-dev.azurewebsites.net \
          --build-arg VUE_APP_ACCESS_SCOPE=api://a7dc07ae-c976-4161-9069-3685e091eec0/access_as_user \
          --build-arg VUE_APP_CLIENT_ID=373a7768-6d2a-4b20-b671-bc1089104a3a

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |

          echo IMAGE_NAME=$IMAGE_NAME

          docker tag image $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
