name: Docker push

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"

    branches:
      - master

env:
  IMAGE_NAME: alvnoas/alvtime-slack-app-prod

jobs:
  # Push image to Docker Hub
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - uses: anchore/scan-action@master
        with:
          image-reference: "image"
          dockerfile-path: "./Dockerfile"
          fail-build: true
          include-app-packages: true
      - name: Anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          echo IMAGE_NAME=$IMAGE_NAME
          docker tag image $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
