name: Docker

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    # Publish `master` branch as Docker `latest` image.
    branches:
      - master

  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

env:
  IMAGE_NAME: alvnoas/alvtime-vue-pwa

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build . --file Dockerfile

  # Push image to Docker Hub
  push_to_docker_hub:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/master')

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image --build-arg VUE_APP_HOST=https://alvtime-api-dev.azurewebsites.net

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |

          echo IMAGE_NAME=$IMAGE_NAME

          docker tag image $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
