name: Docker push dev

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

    branches:
      - dev

env:
  IMAGE_NAME: alvnoas/alvtime-slack-app-dev

jobs:
  # Push image to Docker Hub
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          echo IMAGE_NAME=$IMAGE_NAME
          docker tag image $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
