name: Frontend Build And Deploy

on:
  workflow_call:
    inputs:
      targetEnv:
          required: true
          type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.targetEnv}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Reinstall dependencies
        run: npm install

      - name: Set OpenSSL legacy mode
        run: export NODE_OPTIONS=--openssl-legacy-provider

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Force Node.js 16
        run: |
          echo "export PATH=$(nvm which 16):$PATH" >> $GITHUB_ENV
          echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Use test config
        run: cp public/config.${{inputs.targetEnv}}.json public/config.json  # Copy test config before build

      - name: Build Vue app
        run: npm run build --mode ${{inputs.targetEnv}}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STATICWEBAPP_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUBACTIONDEPLOYMENTCREDENTIALS }}
          action: "upload"
          app_location: "/"  # Adjust if your Vue app is in a subdirectory
          output_location: "dist"  # Vue build output folder
