name: frontend-docker-publish-releases

on:
  push:
    branches:
      - releases/*

env:
  IMAGE_NAME: alvnoas/alvtime-vue-pwa
  IMAGE_NAME_LOCAL: alvnoas/alvtime-vue-pwa-local

jobs:
  # Push image to Docker Hub
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build frontend images
        working-directory: "./packages/frontend"
        run: |
          docker build . --file Dockerfile --tag image \
          --build-arg VUE_APP_API_HOST=https://alvtime-api-prod.azurewebsites.net \
          --build-arg VUE_APP_ACCESS_SCOPE=api://3644a03b-f801-4b67-b487-3353684fe7fc/access_as_user \
          --build-arg VUE_APP_CLIENT_ID=3644a03b-f801-4b67-b487-3353684fe7fc

          docker build . --file Dockerfile --tag image-local \
          --build-arg VUE_APP_API_HOST=http://localhost:3000 \
          --build-arg VUE_APP_ACCESS_SCOPE=https://d8aedd.alvtime-ap-alvtime-api-dev-f9b4e4.westeurope.cloudapp.azure.com/access_as_user \
          --build-arg VUE_APP_CLIENT_ID=373a7768-6d2a-4b20-b671-bc1089104a3a

      # - uses: anchore/scan-action@master
      #   with:
      #     image-reference: $IMAGE_NAME:latest
      #     dockerfile-path: "./packages/frontend/Dockerfile"
      #     fail-build: true
      #     include-app-packages: true

      # - name: Anchore inline scan JSON results
      #   run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

      - name: Log into registry
        working-directory: "./packages/frontend"
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push frontend images
        working-directory: "./packages/frontend"
        run: |

          echo IMAGE_NAME=$IMAGE_NAME

          docker tag image $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

          echo IMAGE_NAME_LOCAL=$IMAGE_NAME_LOCAL

          docker tag image-local $IMAGE_NAME_LOCAL:latest
          docker push $IMAGE_NAME_LOCAL:latest
