name: Frontend Build And Test

on:
  pull_request:
    paths:
      - "packages/frontend/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        working-directory: "./packages/frontend"
        run: docker build . --file Dockerfile --tag image

      - name: Run tests
        working-directory: "./packages/frontend"
        run: |
          docker build . --file Dockerfile --target dev --tag image
          docker run image npm run build
          docker run image npm run test
          docker run image npm run lint
