name: MigrationClient Migrate

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      environment:
        required: true
        type: string
      targetEnv:
        required: true
        type: string

permissions:
  id-token: write

jobs:
  migrate:
    environment: ${{inputs.targetEnv}}
    runs-on: ubuntu-latest
    steps:
      - name: Download MigrationClient artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DB_SUBSCRIPTION_ID }}

      - name: Get GitHub Actions Runner IP
        id: ip
        run: |
          echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Add IP to Azure SQL Firewall
        run: |
          az sql server firewall-rule create \
            --resource-group databases-${{ inputs.targetEnv }}-rg \
            --server alvtime-${{ inputs.targetEnv }}-sql \
            --name AllowGitHubActions \
            --start-ip-address ${{ steps.ip.outputs.ip }} \
            --end-ip-address ${{ steps.ip.outputs.ip }}

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x


      - name: Run MigrationClient
        env:
          DOTNET_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          cd ./publish
          dotnet AlvTime.MigrationClient.dll

      - name: Remove IP from Azure SQL Firewall
        if: always()
        run: |
          az sql server firewall-rule delete \
            --resource-group databases-${{ inputs.targetEnv }}-rg \
            --server alvtime-${{ inputs.targetEnv }}-sql \
            --name AllowGitHubActions