name: MigrationClient workflow runner

on:
    workflow_dispatch:
    push:
        branches:
          - main
        paths:
         - "packages/api/AlvTime.Persistence/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: packages/api/AlvTime.MigrationClient

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: packages/api/AlvTime.MigrationClient

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: packages/api/AlvTime.MigrationClient

      - name: Upload MigrationClient artifact
        uses: actions/upload-artifact@v4
        with:
          name: migrationclient-publish
          path: packages/api/AlvTime.MigrationClient/publish

  migrate-test:
    needs: build
    uses: ./.github/workflows/migrationclient-migrate.yml
    with:
      artifact-name: migrationclient-publish
      environment: Test
      targetEnv: test
    secrets: inherit


  # migrate-prod:
  #   needs: build
  #   uses: ./.github/workflows/migrationclient-migrate.yml
  #   with:
  #     artifact-name: migrationclient-publish
  #     environment: Production
  #     targetEnv: prod
  #   secrets: inherit
