name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image
            
      - name: Scan image
      - uses: anchore/scan-action@master
        with:
          image-reference: "image"
          dockerfile-path: "./Dockerfile"
          fail-build: true
    
      - name: Anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build . --file Dockerfile-dev --tag image
          docker run image npx vue-cli-service lint
          docker run image npx vue-cli-service test:unit
